#default: &default
#  encoding: utf8
#  adapter: mysql2
#  username: root
#  password: 123456
#  pool: 5
#  timeout: 5000
#  socket: /var/run/mysqld/mysqld.sock

development:
  encoding: utf8
  adapter: mysql2
  username: root
  password: 123456
  pool: 5
  timeout: 5000
  database: kuailv-development

test:
  encoding: utf8
  adapter: mysql2
  username: root
  password: 123456
  pool: 5
  timeout: 5000
  database: kuailv-test

production:
  encoding: utf8
  adapter: mysql2
  username: root
  password: zhongren#1234
  pool: 5
  timeout: 5000
  database: kuailv-production
